#!/usr/bin/env python3
"""
Generate INDEX.md — the human-readable vault table of contents.

Auto-regenerated by `memory daily`. Organizes memories by type + recency, and
entities by type with backlink counts. Replaces hand-maintained INDEX.md.

Run:
    python3 -m memoryvault_kit.graph.index
"""
import re
import sys
from pathlib import Path
from collections import defaultdict
from datetime import datetime, timedelta, timezone

VAULT = Path(__import__("os").environ.get("MEMORYVAULT_ROOT") or next((p for p in [Path(__file__).resolve(), *Path(__file__).resolve().parents] if (p / "memories").is_dir() and (p / "entities").is_dir()), (Path.home() / "MemoryVault")))
MEM_DIR = VAULT / "memories"
ENT_DIR = VAULT / "entities"
INDEX = VAULT / "INDEX.md"

# Display order for memory types
MEMORY_TYPE_ORDER = [
    "decision", "project_fact", "event", "reference", "observation",
    "relationship", "user_fact", "feedback", "preference",
]
# Display order for entity types
ENTITY_TYPE_ORDER = [
    "person", "company", "project", "topic", "thing", "place", "role", "unknown",
]


def parse_memory(p):
    text = p.read_text()
    if not text.startswith("---"):
        return None
    parts = text.split("---", 2)
    if len(parts) < 3:
        return None
    fm = {}
    for line in parts[1].splitlines():
        m = re.match(r"^([a-z_]+):\s*(.*)$", line.rstrip())
        if m:
            fm[m.group(1)] = m.group(2).strip()
    entities = re.findall(r"\[\[([^\]]+)\]\]", fm.get("entities", ""))
    try:
        importance = float(fm.get("importance", "0.5"))
    except ValueError:
        importance = 0.5
    return {
        "id": fm.get("id", p.stem),
        "title": fm.get("title", "").strip().strip('"').strip("'"),
        "type": fm.get("type", "unknown").strip(),
        "status": fm.get("status", "active").strip(),
        "importance": importance,
        "created": fm.get("created", ""),
        "entities": entities,
        "path": p,
    }


def parse_entity(p):
    try:
        text = p.read_text()
    except Exception:
        return None
    if not text.startswith("---"):
        return None
    fm = text.split("---", 2)[1]
    name_m = re.search(r"^name:\s*\"?([^\"\n]+)\"?\s*$", fm, re.M)
    type_m = re.search(r"^type:\s*(\S+)", fm, re.M)
    status_m = re.search(r"^status:\s*(\S+)", fm, re.M)
    if not name_m:
        return None
    # Try to extract first sentence of body for the description
    body_start = text.find("---", 3) + 3
    body = text[body_start:].strip()
    desc = body.split(".")[0].strip()[:80] if body else ""
    return {
        "name": name_m.group(1).strip().strip('"').strip("'"),
        "type": (type_m.group(1) if type_m else "unknown").strip(),
        "status": (status_m.group(1) if status_m else "active").strip(),
        "desc": desc,
        "path": p,
    }


def load():
    mems = sorted(
        (m for m in (parse_memory(p) for p in MEM_DIR.rglob("mem_*.md")) if m),
        key=lambda m: (m["created"], m["title"]),
    )
    ents = sorted(
        (e for e in (parse_entity(p) for p in ENT_DIR.rglob("*.md")) if e),
        key=lambda e: e["name"].lower(),
    )
    return mems, ents


def relpath(p):
    """Path relative to vault root, for markdown links."""
    return p.relative_to(VAULT).as_posix()


def build_index():
    mems, ents = load()

    # Entity backlink counts
    backlinks = defaultdict(int)
    for m in mems:
        for e in m["entities"]:
            backlinks[e.lower()] += 1

    today = datetime.now(timezone.utc).date()
    cutoff_30d = today - timedelta(days=30)

    # ── Recent memories (created in last 30 days) ───────────────────
    recent = []
    for m in mems:
        if not m["created"]:
            continue
        try:
            d = datetime.fromisoformat(m["created"].replace("Z", "+00:00")).date()
        except ValueError:
            continue
        if d >= cutoff_30d:
            recent.append((d, m))
    recent.sort(key=lambda x: -x[0].toordinal())

    # ── Memories by type ───────────────────────────────────────────
    by_type = defaultdict(list)
    for m in mems:
        if m["status"] in ("archived", "stub"):
            continue
        by_type[m["type"]].append(m)

    # ── Entities by type (active only, with at least 1 backlink) ───
    by_ent_type = defaultdict(list)
    for e in ents:
        if e["status"] == "stub":
            continue
        if backlinks.get(e["name"].lower(), 0) == 0:
            continue  # skip unlinked
        by_ent_type[e["type"]].append(e)

    n_mems = len(mems)
    n_ents = sum(len(v) for v in by_ent_type.values())
    n_recent = len(recent)

    lines = []
    lines.append(f"# MemoryVault INDEX\n")
    lines.append(f"> Auto-generated by `memory daily`. Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}.\n")
    lines.append(f"**{n_mems} memories**, **{n_ents} live entities**. {n_recent} memories created in last 30 days.\n")
    lines.append("\n---\n")

    # ── Recent section ──────────────────────────────────────────────
    lines.append(f"\n## Recent memories ({n_recent} in last 30d)\n")
    if not recent:
        lines.append("_(no recent memories — vault may be stale)_\n")
    else:
        # Group by date
        by_date = defaultdict(list)
        for d, m in recent:
            by_date[d].append(m)
        for d in sorted(by_date.keys(), reverse=True):
            lines.append(f"\n### {d.isoformat()}\n")
            for m in by_date[d]:
                lines.append(f"- [{m['title']}]({relpath(m['path'])}) — `{m['type']}` (importance {m['importance']:.2f})")

    lines.append("\n---\n")

    # ── Memories by type ───────────────────────────────────────────
    lines.append("\n## All memories by type\n")
    types_present = [t for t in MEMORY_TYPE_ORDER if t in by_type]
    types_other = [t for t in by_type if t not in MEMORY_TYPE_ORDER]
    for t in types_present + types_other:
        items = by_type[t]
        # Sort by importance desc within type, then title
        items.sort(key=lambda m: (-m["importance"], m["title"].lower()))
        lines.append(f"\n### {t} ({len(items)})\n")
        # If a type is big, show only top-importance items + a "see all" hint
        if len(items) > 20:
            for m in items[:15]:
                lines.append(f"- [{m['title']}]({relpath(m['path'])}) (importance {m['importance']:.2f})")
            lines.append(f"- _… and {len(items)-15} more — see `memories/`_")
        else:
            for m in items:
                lines.append(f"- [{m['title']}]({relpath(m['path'])}) (importance {m['importance']:.2f})")

    lines.append("\n---\n")

    # ── Entities by type ───────────────────────────────────────────
    lines.append("\n## Entities by type\n")
    types_present = [t for t in ENTITY_TYPE_ORDER if t in by_ent_type]
    types_other = [t for t in by_ent_type if t not in ENTITY_TYPE_ORDER]
    for t in types_present + types_other:
        items = by_ent_type[t]
        items.sort(key=lambda e: -backlinks.get(e["name"].lower(), 0))
        lines.append(f"\n### {t} ({len(items)})\n")
        for e in items[:25]:
            n = backlinks.get(e["name"].lower(), 0)
            desc = f" — {e['desc']}" if e["desc"] else ""
            lines.append(f"- [{e['name']}]({relpath(e['path'])}) ({n} backlinks){desc}")
        if len(items) > 25:
            lines.append(f"- _… and {len(items)-25} more_")

    text = "\n".join(lines) + "\n"
    INDEX.write_text(text)
    print(f"Wrote {INDEX} ({n_mems} memories, {n_ents} entities, {n_recent} recent)")


if __name__ == "__main__":
    build_index()
